number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'AĂÂBCDĐEÊFGHIJKLMNOÔƠPQRSTUƯVXYZaăâbcdđeêfghijklmnoôơpqrstuưvxyz'  # Updated for Vietnamese
experiment_name: 'vi_filtered'  # Changed to Vietnamese
train_data: 'all_data'
valid_data: 'all_data/vi_val'  # Adjusted for Vietnamese validation data
manualSeed: 1111
workers: 1
batch_size: 10  # Kept as in your input
num_iter: 4  # Kept as in your input, though typically higher for real training
valInterval: 4
saved_model: 'saved_models/vi_filtered/iter_300000.pth'  # Updated path for Vietnamese
FT: False
optim: False  # default is Adadelta
lr: 1.0
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
# Data processing
select_data: 'vi_train_filtered'  # Updated to Vietnamese training dataset
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 10
imgH: 64
imgW: 433
rgb: False
contrast_adjust: False
sensitive: True  # Case sensitivity, useful for Vietnamese tones
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False